# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor 
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    entity_recognition: False
    epochs: 50
    batch_strategy: sequence # if you have a lot of training data for some intents and very little training data for others. 

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 50
    retrieval_intent: nlu-faq-portal-b3-hi

  - name: ResponseSelector
    epochs: 50
    retrieval_intent: nlu-faq-vis-b1-hi

  - name: ResponseSelector
    epochs: 50
    retrieval_intent: nlu-faq-training-b1-hi    

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
